name: '${projectName}'
version: '${projectVersion}'
main: '${projectMainClass}'
api-version: 1.19
authors: [ CKATEPTb ]
depend: [ Nicotine, Caffeine, Varflex ]
description: A set of tools that simplify asynchronous development.